use std::io

extern error struct ExhaustionError {
    message str
}

struct Box { value }

impl Box {
    func new(value) {
        Box(value)
    }
}

struct Atom {
    value str
}

impl Atom {
    func new(value) {
        Atom(value)
    }
}

func panic(message) {
    io.println(message)
    control.exit(1)
}

inline func with(resource, closure) {
    result = closure(resource)
    resource.close()
    result
}

impl<T> T {
    inline func let(self, closure) {
        closure(self)
    }

    inline func also(self, closure) {
        _ = closure(self)
        self
    }

    inline func takeIf(self, closure) {
        if closure(self) self else null
    }

    inline func takeUnless(self, closure) {
        if closure(self) null else self
    }
}